docs: update readme, add custom metrics, better formating
apiaryio/heroku-datadog-drain-golang pull request #28
Opened 2016-10-12 09:27 UTC by abtris

2016-10-12 09:48 UTC, w-vi requested changes

2016-10-12 09:48 UTC, w-vi commented on README.md
> +This add into logs are metrics what you need (cpu, memory etc.).
This adds basic metrics (cpu, memory etc.) into logs.

2016-10-12 09:48 UTC, w-vi commented on README.md
> +If you can log some your custom metrics just log line in this format:
If you want to log some custom metrics just format the log line like following:

2016-10-12 09:48 UTC, w-vi commented on README.md
> +We support `metrics#` for values and `metrics#tag` for tags.
Shouldn't it be `metrics#tag#`?

2016-10-19 06:04 UTC, abtris commented on README.md
> +We support `metrics#` for values and `metrics#tag` for tags.
Good catch!

2016-10-19 06:06 UTC, abtris commented
Updated.

2016-10-19 08:16 UTC, w-vi approved these changes

2016-10-19 08:16 UTC, merged